// <auto-generated />
using System;
using EnglishGamesPlatform.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishGamesPlatform.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // כל הישויות וה־relations לפי הגרסה של finall
            modelBuilder.Entity("EnglishGamesPlatform.Backend.Models.Entities.MissingWordSentence", b =>
            {
                b.Property<int>("MissingWordSentenceId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MissingWordSentenceId"));

                b.Property<int>("CorrectWordId").HasColumnType("int");
                b.Property<int>("SentenceId").HasColumnType("int");

                b.HasKey("MissingWordSentenceId");
                b.HasIndex("CorrectWordId");
                b.HasIndex("SentenceId");

                b.ToTable("MissingWords");
            });

            // שאר הישויות נשארות כמו ב־finall

#pragma warning restore 612, 618
        }
    }
}
